### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by alexmyczko** [reduz/chibitracker#11]
is that possible?

**Comment by danboid** [comment]
I think reduz is a bit preoccupied with godot :)

What an amazing app tho!

**Comment by reduz** [comment]
I'm too lazy to do this.. :\ Haven't maintained it in ages, no idea in which state it is..
I know it compiles on Linux at least. May compile on Windows using Msys2

**Comment by rzr** [comment]
Relate-to: https://github.com/abandonware/abandonware.github.io/issues/5

**Comment by alexmyczko** [comment]
> I think reduz is a bit preoccupied with godot :)

or https://github.com/reduz/zytrax
